// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onCurrAttemptChange();
void onSweetSpotChange();
void onNewNumFlagChange();

float currAttempt;
float sweetSpot;
bool newNumFlag;

void initProperties(){

  ArduinoCloud.addProperty(currAttempt, READWRITE, ON_CHANGE, onCurrAttemptChange);
  ArduinoCloud.addProperty(sweetSpot, READWRITE, ON_CHANGE, onSweetSpotChange);
  ArduinoCloud.addProperty(newNumFlag, READWRITE, ON_CHANGE, onNewNumFlagChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
